[ 2025-06-26 10:23:11,968 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.192.18.70:8000
[ 2025-06-26 10:23:11,970 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-06-26 10:23:46,650 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:23:46] "GET / HTTP/1.1" 200 -
[ 2025-06-26 10:23:46,874 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:23:46] "GET /static/css/style.css HTTP/1.1" 200 -
[ 2025-06-26 10:23:46,895 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:23:46] "[32mGET /static//Image/your_profile_pic.jpg HTTP/1.1[0m" 308 -
[ 2025-06-26 10:23:46,973 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:23:46] "GET /static/Image/your_profile_pic.jpg HTTP/1.1" 200 -
[ 2025-06-26 10:23:47,212 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:23:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2025-06-26 10:24:55,759 ] 61 root - INFO - Dataframe Gathered
[ 2025-06-26 10:24:57,376 ] 93 root - INFO - Exception Occured in load_object function utils
[ 2025-06-26 10:24:57,376 ] 21 root - INFO - Exception occured in prediction pipeline
[ 2025-06-26 10:24:57,376 ] 875 application - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Dhiraj Learning\GameStone Project\src\utils.py", line 91, in load_object
    return dill.load(file_obj)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\dill\_dill.py", line 297, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\dill\_dill.py", line 452, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\dill\_dill.py", line 442, in find_class
    return StockUnpickler.find_class(self, module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'EuclideanDistance' on <module 'sklearn.metrics._dist_metrics' from 'C:\\Users\\ddurande\\AppData\\Roaming\\Python\\Python312\\site-packages\\sklearn\\metrics\\_dist_metrics.cp312-win_amd64.pyd'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dhiraj Learning\GameStone Project\src\pipeline\predict_pipeline.py", line 16, in predict
    model = load_object(file_path=model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dhiraj Learning\GameStone Project\src\utils.py", line 94, in load_object
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Dhiraj Learning\GameStone Project\src\utils.py] line number [91] error message [Can't get attribute 'EuclideanDistance' on <module 'sklearn.metrics._dist_metrics' from 'C:\\Users\\ddurande\\AppData\\Roaming\\Python\\Python312\\site-packages\\sklearn\\metrics\\_dist_metrics.cp312-win_amd64.pyd'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Dhiraj Learning\GameStone Project\application.py", line 37, in predict_datapoint
    pred = predict_pipeline.predict(pred_df)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dhiraj Learning\GameStone Project\src\pipeline\predict_pipeline.py", line 22, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Dhiraj Learning\GameStone Project\src\pipeline\predict_pipeline.py] line number [16] error message [Error occured in python script name [C:\Dhiraj Learning\GameStone Project\src\utils.py] line number [91] error message [Can't get attribute 'EuclideanDistance' on <module 'sklearn.metrics._dist_metrics' from 'C:\\Users\\ddurande\\AppData\\Roaming\\Python\\Python312\\site-packages\\sklearn\\metrics\\_dist_metrics.cp312-win_amd64.pyd'>]]
[ 2025-06-26 10:24:57,382 ] 97 werkzeug - INFO - 127.0.0.1 - - [26/Jun/2025 10:24:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
